### ISSUE TITLE
Please remove allowBackup from library's manifest file.

### ISSUE THREAD

**Issue by dbychkov** [nntuyen/mkloader#8] opened 2017-06-06 15:39 UTC
Please remove allowBackup from library's manifest file.It conflicts with the main app's manifest.

**Comment by nntuyen** [comment] 2017-06-07 03:00
@dbychkov thanks. It will be fixed with next release.

**Comment by nntuyen** [comment] 2017-06-13 10:29
@dbychkov v1.3.0 is released that fix the issue

**Comment by nntuyen** [comment] 2017-06-13 10:31
@dbychkov the issue is fixed in v1.3.0

**Closed by nntuyen** 2017-06-13 10:31 UTC

**Comment by dbychkov** [comment] 2017-06-13 12:56
@nntuyen Thanks!
